### ISSUE TITLE
Bug: countries and servers not appearing

### ISSUE THREAD

**Issue by anoncodingeverything** [chris2k90/plasma-nordvpn#41]
**Describe the bug**
Only two options are present on the widget: auto and albania. Clicking albania gives an error which says "the specified server does not exist". Normally I would see all possible countries and servers I could connect to, however now its only possible to see one and it doesn't work. I have to use the terminal to connect. 

**To Reproduce**
1. add widget Nordvpn Plasmoid
2. upgrade kubuntu to latest version
3. no connection options are shown.

**Expected behavior**
Normally I would see all possible countries and servers I could connect to, however now its only possible to see one and it doesn't work. 

**Screenshots**
![Screenshot_20240725_224722](https://github.com/user-attachments/assets/a5cdd27b-2709-49e1-8aac-a476501dfd82)

**DESKTOP INDO **
Operating System: Kubuntu 24.04
KDE Plasma Version: 5.27.11
KDE Frameworks Version: 5.115.0
NordVPN Version 3.18.3
Qt Version: 5.15.13
Kernel Version: 6.8.0-39-generic (64-bit)
Graphics Platform: Wayland

**Additional context**
This is happening on all my kubuntu computers.

**Comment by korapp** [comment]
Thank you for reporting, but the issue has already been addressed v0.5.1
